config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :reviews

  get    '/reviews/new/:user_id' => 'reviews#new', as: :new_review_for_user
  get    '/users/new/nurse/:nurse'      => 'users#new'   , as: :new_nurse

  delete '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create]

  # get '/users/:id' => 'users#show', as: :user
  # get '/users' => 'users#index', as: :users


  # get 'reviews/index'
  #
  # get 'reviews/show'
  #
  # get 'reviews/new'
  #
  # get 'reviews/create'
  #
  # get 'reviews/edit'
  #
  # get 'reviews/update'
  #
  # get 'reviews/destroy'
  #
  # get 'users/index'
  #
  # get 'users/show'
  #
  # get 'users/new'
  #
  # get 'users/create'
  #
  # get 'users/edit'
  #
  # get 'users/update'
  #
  # get 'users/destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_secure_password
  validates :password, confirmation: true, presence: true
  # validates :password_confirmation, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true
  # validates :city, presence: true
  # validates :state, presence: true
  # validates :nurse_type, presence: true

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  def avg
     divisor = self.reviews.count > 0 ? self.reviews.count : 1
     self.reviews.inject(0) {|sum, el| sum + el.rating unless el.rating.nil? } / divisor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new]

  def index
  end

  def show
  end

  def new
    # @reviews =
    redirect_to root_path unless hasNotReviewed(params[:user_id].to_i)
    p "***&&&&&^^^^^^-----------------------------------------------"
    @review = Review.new
    @review.user_id = params[:user_id]
    @review.user_email = current_user.email
    p "***&&&&&^^^^^^-----------------------------------------------"
    # @user_email = //get current logged in user email address

  end

  def create
    @review = Review.new(review_params)

    if (@review.rating > 0 && @review.rating <= 100 && @review.save)
        redirect_to user_path(@review.user_id)
     else
        redirect_to root_path
     end
  end

  def edit
  end

  def update
  end

  def destroy
    @review = Review.find(params[:id])

    if @review.destroy
      redirect_to user_path(current_user.id)
    else
      redirect_to root_path
    end
  end

  private
  def review_params
    params.require(:review).permit(:body,:rating, :user_id, :user_email)
  end

  # def calcualte_review_score(userID)
  #   user = User.find(userID)
  #   # review_score = calcualte_review_score(@review.user_id)
  #   reviews = User.find(userID).reviews
  #   avg_score = 0
  #   counter = 0
  #   reviews.each do |s|
  #     if s.rating?
  #     counter += 1
  #     avg_score += s.rating
  #     end
  #   end
  # avg_score = avg_score / counter
  # user.average_score = avg_score
  # user.save
  # end

  def hasNotReviewed(id)
    email_address = current_user.email
    reviews = Review.where(user_email: email_address)

    if logged_in?
      reviews.each do |rv|
        if rv.user_id == id
          return false
        end
      end
    else
      return false
    end
    return true
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
       redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit]


  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def show
    @user =  User.find(params[:id])
    @email_address = @user.email
    @reviews = Review.where(user_email: @email_address)
    @display_review_option = hasNotReviewed(@user.id)
  end

  def new
  @user = User.new
  @nurse = true
  @nurse = false unless params[:nurse]
  end

def create
  @user = User.new(user_params)

  if @user.save
     redirect_to root_path
   else
     render 'new'
   end
end

  def edit
    @user = User.find(params[:id])
    redirect_to users_path unless @user == current_user
  end

  def update
    @user = User.find(params[:id])
    # @user.nurse = false
        if @user.update_attributes(user_edit_params)
          redirect_to user_path(params[:id])
        else
          redirect_to edit_user_path(params[:id])
        end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation,:headline, :bio, :city, :state, :nurse_type, :nurse, :agency, :image)
  end

  def user_edit_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation, :headline, :bio, :city, :state, :nurse_type, :nurse, :agency, :image)
  end

  def hasNotReviewed(id)
    if logged_in?
    email_address = current_user.email
    reviews = Review.where(user_email: email_address)

      if reviews
        reviews.each do |rv|
          if rv.user_id == id
            return false
          end
        end
      end
      return true
    else
      return false
    end

    return true
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'partials/navbar' %>


    <title>Nurseview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:alert] %>
      <div class="alert alert-danger">
    	<%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">Nurseview</a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Out of order  ">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <%= form_tag(users_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
        <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Nurses", class:"form-control" %>
        </div>
      <%= submit_tag "Search",  class:"btn btn-default" %>
      <% end %>


      <ul class="nav navbar-nav navbar-right">


        <% if logged_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "My Profile", user_path(current_user) %></li>
                    <li><%= link_to "Edit My Profile", edit_user_path(current_user) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Logout", logout_path, {method: "DELETE"} %></li>
                  </ul>
                </li>


        <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Nurse Sign Up ", new_nurse_path("Nurse") %></li>
        <li><%= link_to "Login", new_session_path %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= form_for @review, :html => {class: 'new_review form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Leave Review:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :body, 'Body*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :body, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :rating, 'Rating*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :rating, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
              <%= f.hidden_field :user_id, :value => @review.user_id %>
                <%= f.hidden_field :user_email, :value => @review.user_email %>
                <%= f.submit 'Submit Review', class: 'btn btn-success' %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Update Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>*
      <%= f.text_field :name, class: 'form-control',  required: true   %><br />

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control',  required: true   %><br />


      <%= f.label :image %>
      <%= f.text_field :image, class: 'form-control' %><br />

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %><br />

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %><br />

      <% if @user.nurse  %>
      <%= f.label :headline %>
      <%= f.text_field :headline, class: 'form-control' %><br />

      <%= f.label :bio %>
      <%= f.text_field :bio, class: 'form-control' %><br />

      <%= f.label :nurse_type %>
      <%= f.text_field :nurse_type, class: 'form-control'%><br />

      <%= f.label :agency %>
      <%= f.text_field :agency, class: 'form-control'%><br />

      <% end  %>




      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control',  required: true   %><br />


      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <%= button_to "Delete Account", @user, :method => :delete, class: "btn btn-danger delete", data: {confirm: "Are you sure?"} %>

    <% end %>

  </div>
</div>

app/views/users/index.html.erb
 <div class="row">
   <% @users.each do |u| %>

      <% if u.nurse %>
        <div class="col-md-2">
          <div class="thumbnail">
            <img src="<%= u.image %>" alt="No Image">
            <div class="caption">
              <h4><%= link_to(u.name, user_path(u)) %></h4>
              <%= u.city %>, <%= u.state %>
              <p style="display:inline; float:right"><%= u.avg == 0 ?  "New User" : (u.avg.to_s + "%")  %></p>
            </div>
          </div>
        </div>

      <% end %>
<% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/error_messages' %>


<%= form_for @user,:html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Create Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :name, 'Name*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :name, class: 'form-control' ,  required: true  %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' ,  required: true  %>
            </div>
        </div>


        <div class="form-group">
            <%= f.label :image, 'Image URL', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :image, class: 'form-control' %>
            </div>
        </div>



        <% if @nurse %>

        <div class="form-group">
            <%= f.label :headline, 'Headline*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :headline, class: 'form-control' ,  required: true  %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :bio, 'Short Bio', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_area :bio, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :city, 'City*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :city, class: 'form-control' ,  required: true  %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :state, 'State*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :state, class: 'form-control' ,  required: true  %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :nurse_type, 'Type (RN, LVN, Student etc.)*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :nurse_type, class: 'form-control' ,  required: true  %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :agency, 'Current Home Health Agency', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :agency, class: 'form-control' %>
            </div>
        </div>

        <%= f.hidden_field :nurse, :value => true %>

        <% else  %>
        <%= f.hidden_field :headline, :value => "N/A" %>
        <%= f.hidden_field :city, :value => "N/A" %>
        <%= f.hidden_field :state, :value => "N/A" %>
        <%= f.hidden_field :nurse_type, :value => "N/A" %>
        <%= f.hidden_field :nurse, :value => false %>
        <% end  %>

        <div class="form-group">
            <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password, class: 'form-control' ,  required: true  %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password_confirmation, class: 'form-control' ,  required: true    %>
            </div>
        </div>


        <center>
          <p>* Required fields</p>
        </center>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <%= f.submit 'Create Account', class: 'btn btn-success' %>
            </div>
        </div>
    </fieldset>

<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

       <div class="col-md-7 ">
<div class="panel panel-default">
  <div class="panel-heading">  <h4 > <%= @user.headline %> </h4></div>
   <div class="panel-body">

    <div class="box box-info">

            <div class="box-body">
                     <div class="col-sm-6">
                     <div  align="center"> <img alt="User Pic" src=" <%= @user.image %> " id="profile-image1" class="img-circle img-responsive">

                <input id="profile-image-upload" class="hidden" type="file">

                     </div>

              <br>

              <!-- /input-group -->
            </div>
            <div class="col-sm-6">
            <h4 style="color:#00b1b1;"> <%= @user.name %> </h4></span>

              <% if @user.nurse %>
              <span><p>Review Score: <%= @user.avg %>% (<%= @user.reviews.count %>)</p></span>
              <% end %>
              <%  if @display_review_option || !(logged_in?)%>

                  <%= link_to 'Leave Review', new_review_for_user_path(@user.id), :class => "btn" unless @user == current_user ||  @user.nurse == false %>

              <% else  %>
              <p><%= "Thanks for your review!" %></p>
              <% end  %>

            </div>
            <div class="clearfix"></div>
            <hr style="margin:5px 0 5px 0;">


<div class="col-sm-5 col-xs-6 tital " >Name:</div><div class="col-sm-7 col-xs-6 "> <%= @user.name %> </div>
     <div class="clearfix"></div>
<div class="bot-border"></div>

<div class="col-sm-5 col-xs-6 tital " >City:</div><div class="col-sm-7">  <%= @user.city %> </div>
  <div class="clearfix"></div>
<div class="bot-border"></div>

<div class="col-sm-5 col-xs-6 tital " >State:</div><div class="col-sm-7">  <%= @user.state %> </div>
  <div class="clearfix"></div>
<div class="bot-border"></div>

<% if @user.nurse %>
<div class="col-sm-5 col-xs-6 tital " >Type:</div><div class="col-sm-7"> <%= @user.nurse_type %> </div>
  <div class="clearfix"></div>
<div class="bot-border"></div>

<div class="col-sm-5 col-xs-6 tital " >Agency:</div><div class="col-sm-7"> <%= @user.agency %> </div>

 <div class="clearfix"></div>
<div class="bot-border"></div>
<% end  %>

            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>


    </div>
    </div>
</div>

<div class= "col-md-5 ">


  <% if @user.nurse  %>
    <% @user.reviews.each do |rv| %>

      <!-- Start of Review Colum +++++++++++++++++++++  -->
        <div class="col-md-12">
                  <div class="panel panel-default">
                  <div class="panel-heading">
                    <span itemscope itemtype="http://schema.org/Review">
                    <h3 class="panel-title" itemprop="name"><p><%= User.find_by(email: rv.user_email).name if User.find_by(email: rv.user_email) %> </p>
</h3>
                  </div><!--/panel-heading-->
                  <div class="panel-body" itemprop="reviewBody">
                    <p> <%=  rv.body %> </p>

                      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>

                      <meta itemprop="datePublished" content=" <%=  rv.created_at %> "> <%= rv.created_at  %>

                      <span class="pull-right">
                      <span class="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <meta itemprop="worstRating" content="1">
                          <span itemprop="ratingValue"> <%= rv.rating %> </span></span>
                        <span itemprop="bestRating"> % </span>
                      </span><!--/reviewRating-->

                    </small>
                  </div><!--/panel-body-->
                  <div class="panel-footer clearfix">

                  </div><!--/panel-footer-->
                </div><!--/panel-->
              </div><!--/col-sm-6-->
      <!-- END of Review Colum +++++++++++++++++++++  -->

    <% end %>
  <% end %>





  <% if @user.nurse == false and @user.id == current_user.id  %>

  <% @reviews.each do |rv| %>


  <!-- Start of Review Colum +++++++++++++++++++++  -->
    <div class="col-md-12">
              <div class="panel panel-default">
              <div class="panel-heading">
                <span itemscope itemtype="http://schema.org/Review">
                <h4 class="panel-title" itemprop="name"> <%= User.find(rv.user_id).name %>
                  <%= button_to "Delete Review", rv, :method => :delete,  :class => 'btn btn-sm btn-primary', data: {confirm: "Are you sure?"} %>  </h4>
              </div><!--/panel-heading-->
              <div class="panel-body" itemprop="reviewBody">
                <p> <%=  rv.body %> </p>

                  <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>

                  <meta itemprop="datePublished" content=" <%=  rv.created_at %> "> <%= rv.created_at  %>

                  <span class="pull-right">
                  <span class="reviewRating" itemscope itemtype="http://schema.org/Rating">
                    <meta itemprop="worstRating" content="1">
                      <span itemprop="ratingValue"> <%= rv.rating %> </span></span>
                    <span itemprop="bestRating"> % </span>
                  </span><!--/reviewRating-->

                </small>
              </div><!--/panel-body-->
              <div class="panel-footer clearfix">

              </div><!--/panel-footer-->
            </div><!--/panel-->
          </div><!--/col-sm-6-->

    <% end %>
  <% end %>


</div> <!--/col-md-5-->
    <!-- <script>
              $(function() {
    $('#profile-image1').on('click', function() {
        $('#profile-image-upload').click();
    });
});
              </script> -->
   </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>